---
branches:
- main
plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
- - "@google/semantic-release-replace-plugin"
  - replacements:
    - files:
      - gradle.properties
      from: version=.*
      to: version=${nextRelease.version}
      results:
      - file: gradle.properties
        hasChanged: true
        numMatches: 1
        numReplacements: 1
      countMatches: true
- - "@semantic-release/changelog"
  - changelogTitle: "# Changelog"
- - "@semantic-release/git"
  - assets:
    - gradle.properties
    - CHANGELOG.md
    message: |-
      chore: release v${nextRelease.version}

      ${nextRelease.notes}
- "@semantic-release/github"
